rush-f/RUSH-C

frontend/rush/README.md, frontend/rush/package.json, frontend/rush/public/index.html, frontend/rush/src/components/Map.js, frontend/rush/src/components/button/MenuButton.js, frontend/rush/src/components/button/styled.css, frontend/rush/yarn.lock
**작업 내용**
1. 정보창
2. 스타일 컴포넌트
3. 버거메뉴 디자인 조정
4. 그룹토글 구현
**테스트 작성 여부**
**주의 사항**
=> feat: 4월 2일 페어프로그래밍 

frontend/rush/src/components/button/GroupList.js
**이슈 번호**
**작업 내용**
**테스트 작성 여부**
**주의 사항**
=> fix: 누락된 파일 추가

frontend/rush/src/components/WritingMap.js, frontend/rush/src/components/page/writingPage/WritingStep1Page.js, frontend/rush/yarn.lock
**작업 내용**
1. 글쓰기 step1 - 마커를 지도 중앙에 고정
2. 글쓰기 step1 - 지도 중앙 좌표를 부모에서 관리
**테스트 작성 여부**
**주의 사항**
=> feat: 4월 8일 페어프로그래밍

frontend/rush/src/components/WindowSize.js, frontend/rush/src/components/home/DefaultMapPage.js, frontend/rush/src/components/postDetail/Box.js, frontend/rush/src/components/postDetail/PostDetailPage.js, frontend/rush/src/components/postDetail/PostMeta.js, frontend/rush/src/components/postDetail/Profile.js, frontend/rush/src/components/writing/WritingPage.js, frontend/rush/src/components/writing/step2/StyledTextarea.js, frontend/rush/src/components/writing/step2/WritingStep2Modal.js, frontend/rush/src/components/writing/step3/WritingStep3Modal.js, frontend/rush/src/index.css
**작업 내용**
1. 지도 및 글쓰기 step2, 3 컨텐츠 높이를 화면에 맞게 조정
2. 글상세 페이지 레이아웃
**테스트 작성 여부**
=> feat: 4월 23일 페어프로그래밍

backend/rush/build.gradle, backend/rush/http/article.http, backend/rush/src/main/java/rush/rush/controller/ArticleController.java, backend/rush/src/main/java/rush/rush/domain/Article.java, backend/rush/src/main/java/rush/rush/dto/ArticleResponse.java, backend/rush/src/main/java/rush/rush/dto/CreateArticleRequest.java, backend/rush/src/main/java/rush/rush/service/ArticleService.java, backend/rush/src/test/java/rush/rush/acceptance/ArticleAcceptanceTest.java, backend/rush/src/test/java/rush/rush/domain/ArticleTest.java, backend/rush/src/test/java/rush/rush/service/ArticleServiceTest.java
**작업 내용**
1. Article create API 테스트 구현
2. Article create 서비스 테스트 구현
3. Article 조회기능 구현
**테스트 작성 여부**
**주의 사항**
=> feat: 4월 29일 페어프로그래밍

frontend/rush/src/components/articleDetail/ArticleBody.js, frontend/rush/src/components/articleDetail/ArticleContent.js, frontend/rush/src/components/articleDetail/ArticleDetailPage.js, frontend/rush/src/components/articleDetail/ArticleMeta.js, frontend/rush/src/components/articleDetail/ArticleTitle.js, frontend/rush/src/components/articleDetail/CreateDate.js, frontend/rush/src/components/writing/WritingPage.js, frontend/rush/src/components/writing/step3/WritingStep3Modal.js
**작업 내용**
1. 글상세 페이지 디자인 조정
2. 글 작성 페이지 리팩토링
**테스트 작성 여부**
=> feat: 5월 3일 페어프로그래밍

backend/rush/.gitignore, backend/rush/build.gradle, backend/rush/src/main/java/rush/rush/RushApplication.java, backend/rush/src/main/java/rush/rush/config/WebConfig.java, backend/rush/src/main/java/rush/rush/domain/AuthProvider.java, backend/rush/src/main/java/rush/rush/domain/User.java, backend/rush/src/main/java/rush/rush/repository/UserRepository.java, backend/rush/src/main/java/rush/rush/security/AppProperties.java, backend/rush/src/main/resources/application.yml
**작업 내용**
1. 스프링 시큐리티 코딩 시작
**테스트 작성 여부**
**주의 사항**
=> feat: 5월 6일 페어프로그래밍

backend/rush/build.gradle, backend/rush/src/main/java/rush/rush/config/SecurityConfig.java, backend/rush/src/main/java/rush/rush/controller/AuthController.java, backend/rush/src/main/java/rush/rush/controller/UserController.java, backend/rush/src/main/java/rush/rush/domain/User.java, backend/rush/src/main/java/rush/rush/dto/AuthResponse.java, backend/rush/src/main/java/rush/rush/dto/LoginRequest.java, backend/rush/src/main/java/rush/rush/dto/SignUpRequest.java, backend/rush/src/main/java/rush/rush/security/BadRequestException.java, backend/rush/src/main/java/rush/rush/security/CookieUtils.java, backend/rush/src/main/java/rush/rush/security/CurrentUser.java, backend/rush/src/main/java/rush/rush/security/HttpCookieOAuth2AuthorizationRequestRepository.java, backend/rush/src/main/java/rush/rush/security/OAuth2AuthenticationFailureHandler.java, backend/rush/src/main/java/rush/rush/security/OAuth2AuthenticationProcessingException.java, backend/rush/src/main/java/rush/rush/security/OAuth2AuthenticationSuccessHandler.java, backend/rush/src/main/java/rush/rush/security/ResourceNotFoundException.java, backend/rush/src/main/java/rush/rush/security/RestAuthenticationEntryPoint.java, backend/rush/src/main/java/rush/rush/security/TokenAuthenticationFilter.java, backend/rush/src/main/java/rush/rush/security/TokenProvider.java, backend/rush/src/main/java/rush/rush/security/service/CustomOAuth2UserService.java, backend/rush/src/main/java/rush/rush/security/service/CustomUserDetailsService.java, backend/rush/src/main/java/rush/rush/security/user/GoogleOAuth2UserInfo.java, backend/rush/src/main/java/rush/rush/security/user/OAuth2UserInfo.java, backend/rush/src/main/java/rush/rush/security/user/OAuth2UserInfoFactory.java, backend/rush/src/main/java/rush/rush/security/user/UserPrincipal.java, backend/rush/src/main/java/rush/rush/utils/HashUtil.java
**작업 내용**
1. 구글 소셜로그인
2. 일반 회원 회원가입 & 로그인
**테스트 작성 여부**
**주의 사항**
=> feat: 5월 7일 페어프로그래밍

backend/rush/src/main/java/rush/rush/RushApplication.java, backend/rush/src/main/resources/application-local.yml, backend/rush/src/main/resources/application.yml
**작업 내용**
1. 실서버/로컬 yml 분리
**테스트 작성 여부**
**주의 사항**
=> feat: 5월 24일 페어프로그래밍

backend/rush/src/main/java/rush/rush/RushApplication.java, backend/rush/src/main/resources/application-local.yml, backend/rush/src/main/resources/application.yml
**이슈 번호**
resolved: #41 
**작업 내용**
1. 실서버/로컬 환경 분리
**테스트 작성 여부**
**주의 사항**
=> feat: 실서버/로컬 환경 분리

backend/rush/build.gradle
**작업 내용**
1. mysql dependency 추가
**테스트 작성 여부**
**주의 사항**
=> feat: mysql dependency 추가

frontend/rush/src/components/articleDetail/FindWritingApi.js, frontend/rush/src/components/home/FindPublicMapArticlesApi.js, frontend/rush/src/components/home/FindUserImageUrlApi.js, frontend/rush/src/components/login/LoginPage.js, frontend/rush/src/components/writing/CreateWritingApi.js, frontend/rush/src/constants/ADDRESS.js, frontend/rush/src/constants/BackendAddress.js
**작업 내용**
1. 실서버 주소 적용
**테스트 작성 여부**
**주의 사항**
=> feat: 5월 26일 페어프로그래밍

backend/rush/src/main/java/rush/rush/config/WebConfig.java
**이슈 번호**
resolved: #50 
**작업 내용**
1. 실서버 CORS 문제 해결
**테스트 작성 여부**
**주의 사항**
=> feat: 실서버 CORS 문제 해결

frontend/rush/src/components/articleDetail/ArticleMeta.js, frontend/rush/src/components/articleDetail/CancelButton.js, frontend/rush/src/components/home/DefaultMap.js, frontend/rush/src/components/home/button/MenuButton.js, frontend/rush/src/components/home/button/groupMap/GroupContent.js, frontend/rush/src/components/login/LoginPage.js, frontend/rush/src/components/writing/WritingPage.js, frontend/rush/src/components/writing/step1/WritingMap.js, frontend/rush/src/util/PostPositionSpreader.js
**작업 내용**
1. 아직 개발중입니다 추가
2. 마커위치 중복시 흩어지게 함
3. 글쓰기, 글상세 x 버튼 분리
4. 글쓰기 1단계에서 줌 in/out 시 마커가 안따라오는 문제 해결
**테스트 작성 여부**
**주의 사항**
=> feat: 5월 28일 페어프로그래밍

frontend/rush/src/components/articleDetail/ArticleMeta.js, frontend/rush/src/components/articleDetail/CancelButton.js, frontend/rush/src/components/home/DefaultMap.js, frontend/rush/src/components/home/button/MenuButton.js, frontend/rush/src/components/home/button/groupMap/GroupContent.js, frontend/rush/src/components/login/LoginPage.js, frontend/rush/src/components/writing/WritingPage.js, frontend/rush/src/components/writing/step1/WritingMap.js, frontend/rush/src/util/PostPositionSpreader.js
**이슈 번호**
resolved: #53 
**작업 내용**
1. 아직 개발중입니다 추가
2. 마커위치 중복시 흩어지게 함
3. 글쓰기, 글상세 x 버튼 분리
4. 글쓰기 1단계에서 줌 in/out 시 마커가 안따라오는 문제 해결
**테스트 작성 여부**
**주의 사항**
=> feat: 프론트 지도 몇가지 문제 해결

backend/rush/http/comment.http, backend/rush/src/main/java/rush/rush/config/SecurityConfig.java, backend/rush/src/main/java/rush/rush/controller/CommentController.java, backend/rush/src/main/java/rush/rush/dto/AuthorResponse.java, backend/rush/src/main/java/rush/rush/dto/CommentResponse.java, backend/rush/src/main/java/rush/rush/dto/CreateCommentRequest.java, backend/rush/src/main/java/rush/rush/service/ArticleService.java, backend/rush/src/main/java/rush/rush/service/CommentService.java, backend/rush/src/test/java/rush/rush/service/CommentServiceTest.java, frontend/rush/src/components/articleDetail/ArticleDetailPage.js, frontend/rush/src/components/articleDetail/Comment.js, frontend/rush/src/components/articleDetail/CommentWriting.js, frontend/rush/src/components/articleDetail/CreateCommentApi.js, frontend/rush/src/components/articleDetail/FindCommentsApi.js
**작업 내용**
1. 댓글 작성 및 조회 백엔드 구현
2. 댓글 작성 및 조회 프론트엔드&백엔드 연동
**테스트 작성 여부**
**주의 사항**
=> feat: 5월 31일 페어프로그래밍

backend/rush/http/comment.http, backend/rush/src/main/java/rush/rush/RushApplication.java, backend/rush/src/main/java/rush/rush/config/SecurityConfig.java, backend/rush/src/main/java/rush/rush/controller/CommentController.java, backend/rush/src/main/java/rush/rush/domain/Comment.java, backend/rush/src/main/java/rush/rush/dto/AuthorResponse.java, backend/rush/src/main/java/rush/rush/dto/CommentResponse.java, backend/rush/src/main/java/rush/rush/dto/CreateCommentRequest.java, backend/rush/src/main/java/rush/rush/repository/CommentRepository.java, backend/rush/src/main/java/rush/rush/service/ArticleService.java, backend/rush/src/main/java/rush/rush/service/CommentService.java, backend/rush/src/main/resources/application.yml, backend/rush/src/test/java/rush/rush/repository/CommentRepositoryTest.java, backend/rush/src/test/java/rush/rush/service/CommentServiceTest.java, frontend/rush/src/components/articleDetail/ArticleDetailPage.js, frontend/rush/src/components/articleDetail/Comment.js, frontend/rush/src/components/articleDetail/CommentWriting.js, frontend/rush/src/components/articleDetail/CreateCommentApi.js, frontend/rush/src/components/articleDetail/FindCommentsApi.js
**이슈 번호**
resolved: #56 
**작업 내용**
1. 댓글 작성 및 조회 백엔드 API 구현
2. 댓글 작성 및 조회 프론트엔드&백엔드 연동
**테스트 작성 여부**
**주의 사항**
=> feat: 댓글 작성 및 조회 기능

frontend/rush/src/components/articleDetail/ArticleDetailPage.js, frontend/rush/src/components/articleDetail/ArticleMeta.js, frontend/rush/src/components/articleDetail/CancelButton.js, frontend/rush/src/components/home/DefaultMap.js, frontend/rush/src/components/home/DefaultMapPage.js, frontend/rush/src/components/login/OAuth2RedirectHandler.js, frontend/rush/src/components/writing/CreateWritingApi.js
**이슈 번호**
resolved: #64
**작업 내용**
1. articledetail page에서 closebutton 누를시 해당 게시 글의 좌표로 이동
**테스트 작성 여부**
**주의 사항**
=> feat: articledetail page에서 closebutton 누를시 해당 게시 글의 좌표로 이동

backend/rush/src/main/java/rush/rush/RushApplication.java
**이슈 번호**
resolved: #63 
**작업 내용**
1. main 메서드 파라미터로 실서버&로컬 환경 분리
**테스트 작성 여부**
**주의 사항**
=> feat: main 메서드 파라미터로 실서버&로컬 환경 분리

backend/rush/README.md, backend/rush/src/main/java/rush/rush/RushApplication.java
**이슈 번호**
resolved: #70  
**작업 내용**
1. main 메서드 개선
2. 백엔드 실행방법 문서화
**테스트 작성 여부**
**주의 사항**
=> feat: 실서버/로컬 설정분리 코드 개선

backend/rush/src/main/java/rush/rush/config/WebConfig.java
**이슈 번호**
resolved: #76 
**작업 내용**
1. CORS allowedOrigin 실서버 프론트엔드 주소(포트번호) 변경
**테스트 작성 여부**
**주의 사항**
=> feat: CORS allowedOrigin 실서버 프론트엔드 주소(포트번호) 변경

frontend/rush/src/index.js
**이슈 번호**
resolved: #37 
**작업 내용**
1. 클러스터링 숫자가 잘못나오는 오류 해결
**테스트 작성 여부**
**주의 사항**
=> fix: 클러스터링 숫자가 잘못나오는 오류 해결

frontend/rush/src/components/home/DefaultMap.js
**이슈 번호**
resolved: #86 
**작업 내용**
1. 맵의 범위를 지정
**테스트 작성 여부**
**주의 사항**
=> fix: 맵의 범위를 지정

backend/rush/src/main/java/rush/rush/controller/ArticleController.java, backend/rush/src/main/java/rush/rush/repository/ArticleRepository.java, backend/rush/src/main/java/rush/rush/service/ArticleService.java, frontend/rush/src/components/home/DefaultMap.js, frontend/rush/src/components/home/DefaultMapPage.js, frontend/rush/src/components/home/FindPublicMapArticlesApi.js
**이슈 번호**
resolved: #36 
**작업 내용**
1. findPublicMapArticles() 이일부 article 들만 내려주도록 구현
**테스트 작성 여부**
**주의 사항**
=> feat: findPublicMapArticles() 이일부 article 들만 내려주도록 구현

frontend/rush/src/components/writing/step1/WritingMap.js
**이슈 번호**
resolved: #91 
**작업 내용**
1. WritingMap 설정에 defaultOptions 변경(DefaultMap과 동일하게 적용)
**테스트 작성 여부**
**주의 사항**
=> refactor: WritingMap 설정에 defaultOptions 변경(DefaultMap과 동일하게 적용)

backend/rush/src/main/java/rush/rush/security/user/NaverOAuth2UserInfo.java, backend/rush/src/main/java/rush/rush/security/user/OAuth2UserInfoFactory.java, backend/rush/src/main/java/rush/rush/service/UserService.java, frontend/rush/src/components/home/button/Menu/MyPage/Info.js, frontend/rush/src/components/home/button/Menu/MyPage/MyPage.js, frontend/rush/src/components/login/LoginPage.js
**이슈 번호**
resolved: #98 , #99 
**작업 내용**
1. 네이버 로그인 구현(real-server-assets 에 application-oauth.yml 수정함)
2. 로그아웃 기능 구현
**테스트 작성 여부**
**주의 사항**
=> feat: 네이버로그인, 로그아웃 기능 구현

frontend/rush/src/components/home/DefaultMapPage.js, frontend/rush/src/components/home/button/MenuButton.js, frontend/rush/src/components/home/group/GroupList.js, frontend/rush/src/components/home/group/create/CancelButton.js, frontend/rush/src/components/home/group/create/CreateGroupModal.js, frontend/rush/src/components/home/group/join/CancelButton.js, frontend/rush/src/components/home/group/join/JoinGroupModal.js
**이슈 번호**
resolved: #110 
**작업 내용**
1. 그룹만들기, 그룹가입하기 클릭시 매뉴닫히게 수정
2. 그룹만글기, 그룹가입하기에서 취소버튼, 매뉴바의 취소버튼 누를시 그룹이 자동으로 닫히게 수정
**테스트 작성 여부**
**주의 사항**
=> refactor: 매뉴 그룹관련 문제 해결

frontend/rush/src/constants/ADDRESS.js
**이슈 번호**
resolved: #124 
**작업 내용**
실서버 백엔드 주소 80으로 변경
**테스트 작성 여부**
**주의 사항**
=> feat: 실서버 백엔드 주소 80으로 변경

frontend/rush/src/constants/ADDRESS.js
**이슈 번호**
resolved: #109 
**작업 내용**
1. 실서버 백엔드 주소 https 로 변경
**테스트 작성 여부**
**주의 사항**
=> feat: 실서버 백엔드 주소 https 로 변경

backend/rush/src/main/java/rush/rush/config/WebConfig.java
**이슈 번호**
resolved: #126 
**작업 내용**
CORS 허용 주소 https 로 변경
**테스트 작성 여부**
**주의 사항**
=> fix: CORS 허용 주소 https 로 변경

backend/rush/http/article-delete.http, backend/rush/http/article-find.http, backend/rush/src/main/java/rush/rush/controller/DeleteArticleController.java, backend/rush/src/main/java/rush/rush/controller/FindArticleController.java, backend/rush/src/main/java/rush/rush/domain/Article.java, backend/rush/src/main/java/rush/rush/domain/ArticleLike.java, backend/rush/src/main/java/rush/rush/domain/Comment.java, backend/rush/src/main/java/rush/rush/repository/ArticleRepository.java, backend/rush/src/main/java/rush/rush/service/DeleteArticleService.java, backend/rush/src/main/java/rush/rush/service/FindArticleService.java, backend/rush/src/test/java/rush/rush/repository/ArticleLikeRepositoryTest.java, backend/rush/src/test/java/rush/rush/repository/ArticleRepositoryTest.java, backend/rush/src/test/java/rush/rush/repository/CommentRepositoryTest.java, backend/rush/src/test/java/rush/rush/repository/RepositoryTest.java, backend/rush/src/test/java/rush/rush/repository/SetUpMethods.java, frontend/rush/src/api/DeleteArticleApi.js, frontend/rush/src/api/IsMyArticleApi.js, frontend/rush/src/components/articleDetail/ArticleBody.js, frontend/rush/src/components/articleDetail/ArticleDetailPage.js, frontend/rush/src/components/articleDetail/DeleteButton.js
**이슈 번호**
resolved: #133 
**작업 내용**
글 삭제 구현
**테스트 작성 여부**
**주의 사항**
=> feat: 글 삭제 구현

frontend/rush/src/components/home/button/MenuButton.js
**이슈 번호**
resolved: #152 
**작업 내용**
**테스트 작성 여부**
**주의 사항**
=> feat: 메뉴바 문구 개선

backend/rush/src/main/java/rush/rush/domain/Article.java, backend/rush/src/main/java/rush/rush/domain/ArticleGroup.java, backend/rush/src/main/java/rush/rush/domain/ArticleLike.java, backend/rush/src/main/java/rush/rush/domain/Group.java, backend/rush/src/main/java/rush/rush/domain/User.java, backend/rush/src/main/java/rush/rush/domain/UserGroup.java, backend/rush/src/test/java/rush/rush/domain/ArticleTest.java, backend/rush/src/test/java/rush/rush/domain/GroupTest.java, backend/rush/src/test/java/rush/rush/domain/UserTest.java
**이슈 번호**
resolved: #155 
**작업 내용**
1. @Builder 위치를 class에서 생성자로 이동
2. 도메인 테스트 강화
**테스트 작성 여부**
**주의 사항**
=> fix: 실서버 warning 해결 시도

backend/rush/src/main/java/rush/rush/repository/ArticleRepository.java
**이슈 번호**
resolved: #[issue number]
**작업 내용**
ArticleRepository findArticleAuthorId JPQL에 distinct 키워드 붙임
**테스트 작성 여부**
**주의 사항**
=> fix: 실서버에서 삭제기능이 정상동작하지 않는 문제 해결

backend/rush/src/main/java/rush/rush/repository/ArticleRepository.java
**이슈 번호**
resolved: #157 
**작업 내용**
1. 잘못된 JPQL 고침..
**테스트 작성 여부**
**주의 사항**
=> fix: JPQL 잘못된 부분 찾아서 고침

backend/rush/src/main/java/rush/rush/domain/Comment.java
**이슈 번호**
resolved: #165 
**작업 내용**
Comment commentLikes 필드에 orphanRemoval=true 적용
**테스트 작성 여부**
**주의 사항**
=> feat: Comment commentLikes 필드에 orphanRemoval=true 적용

backend/rush/src/main/java/rush/rush/controller/FindArticleController.java, backend/rush/src/main/java/rush/rush/service/FindArticleService.java, frontend/rush/src/api/FindMyIdApi.js, frontend/rush/src/components/articleDetail/ArticleDetailPage.js
**이슈 번호**
resolved: #183 
**작업 내용**
1. bug fix - 프론트엔드 코드 수정
2. refactor - 백엔드 사용되지 않는 api 제거
**테스트 작성 여부**
**주의 사항**
=> fix: 비로그인 사용자가 전체지도 글도 못보는 문제

backend/rush/src/main/java/rush/rush/RushApplication.java, backend/rush/src/main/java/rush/rush/environment/Profile.java
**이슈 번호**
resolved: #176 
**작업 내용**
1. /app/config/ 마지막 슬래시 붙임
2. 실서버에서 application-real 사용하도록 수정
**테스트 작성 여부**
**주의 사항**
=> fix: 백엔드 무중단배포를 위한 백엔드코드 변경사항 수정

frontend/rush/package.json
**이슈 번호**
resolved: #176 
**작업 내용**
package.json 에서 "proxy": "http://localhost:8080" 제거
**테스트 작성 여부**
**주의 사항**
=> fix: package.json 에서 "proxy": "http://localhost:8080" 제거

backend/rush/src/main/java/rush/rush/domain/LocationRange.java, frontend/rush/src/api/DeleteArticleApi.js, frontend/rush/src/components/articleDetail/ArticleBody.js, frontend/rush/src/components/articleDetail/DeleteButton.js
**이슈 번호**
resolved: #182 
**작업 내용**
1. 글 삭제시 홈화면에서 글을 삭제한 좌표로 위치하도록 수정 
**테스트 작성 여부**
**주의 사항**
=> reafector: 글 삭제시 홈화면에서 글을 삭제한 좌표로 위치하도록 수정 

backend/rush/src/main/java/rush/rush/controller/article/FindArticleController.java, backend/rush/src/main/java/rush/rush/dto/ArticleRangeRequest.java
**이슈 번호**
resolved: #199 
**작업 내용**
지도 위 글목록 조회 RequestParam에 DTO 적용
**테스트 작성 여부**
**주의 사항**
=> refactor: 지도 위 글목록 조회 RequestParam에 DTO 적용

frontend/rush/src/components/home/DefaultMapPage.js, frontend/rush/src/components/home/button/MyLocationButton.js, frontend/rush/src/components/writing/MyLocationButton.js
**이슈 번호**
resolved: #209 
**작업 내용**
1. 위치 권한을 허용하지 않을시 처음 로드되는 center를 초기화하는 문제 해결
2. 위치 권한을 허용하지 않으면 현위치 버튼을 누를 시 위치 권한을 재요청하라는 알림을 추가
**테스트 작성 여부**
**주의 사항**
=> fix: gps 권한을 허용하지 않으면 생기는 문제수정

frontend/rush/src/components/home/DefaultMap.js
**이슈 번호**
resolved: #197 
**작업 내용**
1. defaultMap에서 경도를 제한을 둠(글 작성때는 제한을 두지 않아서 글 작성에 제한x)
**테스트 작성 여부**
**주의 사항**
=> refactor: defaultMap에서 경도를 제한을 둠

frontend/rush/src/components/articleDetail/ArticleBody.js
**이슈 번호**
resolved: #196 
**작업 내용**
1. 글작성 줄바꿈 되도록 수정
**테스트 작성 여부**
**주의 사항**
=> refactor: 글작성 줄바꿈 되도록 수정

frontend/rush/src/components/home/menu/Menu.js, frontend/rush/src/components/home/menu/group/GroupContent.js
**이슈 번호**
resolved: #218 
**작업 내용**
1. 중요그룹에 그룹 바로가기 버튼 구현
**테스트 작성 여부**
**주의 사항**
=> feat: 중요그룹에 그룹 바로가기 버튼 구현

frontend/rush/src/api/article/CreateWritingApi.js, frontend/rush/src/api/article/DeleteArticleApi.js, frontend/rush/src/api/article/FindWritingApi.js, frontend/rush/src/api/comment/CreateCommentApi.js, frontend/rush/src/api/group/CreateGroupApi.js, frontend/rush/src/api/group/FindGroupApi.js, frontend/rush/src/api/group/FindGroupMembersApi.js, frontend/rush/src/api/group/FindMyGroupsApi.js, frontend/rush/src/components/articleDetail/ArticleBody.js, frontend/rush/src/components/articleDetail/DeleteButton.js, frontend/rush/src/components/home/DefaultMapPage.js
**이슈 번호**
resolved: #229 
**작업 내용**
1. deleteArticleApi에서 history.push를 수정하여 에러가 안나게 함
2. findApi 에서 에러 발생시 홈으로 가도록 함
**테스트 작성 여부**
**주의 사항**
=> fix: 프론트 api 관련 버그 수정

backend/rush/src/test/java/rush/rush/service/article/FindArticleServiceTest.java
**이슈 번호**
resolved: #231 
**작업 내용**
1. 위도상한에 맞게 articleServiceTest 수정
**테스트 작성 여부**
**주의 사항**
=> fix: 위도상한에 맞게 articleServiceTest 수정

backend/rush/src/test/java/rush/rush/api/article/create/CreateGroupMapArticleTest.java, backend/rush/src/test/java/rush/rush/api/article/create/CreatePrivateMapArticleTest.java, backend/rush/src/test/java/rush/rush/api/article/create/CreatePublicMapArticleTest.java, backend/rush/src/test/java/rush/rush/api/article/findList/FindPublicArticlesTest.java, backend/rush/src/test/java/rush/rush/api/fixture/CreateArticleFixture.java, backend/rush/src/test/java/rush/rush/api/fixture/FindArticleFixture.java
**이슈 번호**
resolved: #225 
**작업 내용**
1. 온누리 발자국 글목록 조회 api테스트
**테스트 작성 여부**
**주의 사항**
=> test: 온누리 발자국 글목록 조회 api테스트
